# Generated by Django 3.2.13 on 2022-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Имя пользователя')),
                ('crypto_ticker', models.TextField(verbose_name='Тикер криптовалюты')),
                ('token_count', models.TextField(verbose_name='Количество токенов')),
                ('usd_count', models.TextField(verbose_name='Стоймость в долларах')),
                ('usd_in', models.TextField(verbose_name='Вложено')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAvatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Имя пользователя')),
                ('imgur_link', models.TextField(verbose_name='Ссылка на аватарку')),
            ],
        ),
    ]
