# Generated by Django 3.2.13 on 2022-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbill',
            name='usd_in',
            field=models.TextField(verbose_name='Вложения в долларах'),
        ),
    ]
