# Generated by Django 3.2.13 on 2022-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_alter_userbill_usd_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCryptoAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Имя пользователя')),
                ('crypto_ticker', models.TextField(verbose_name='Тикер криптовалюты')),
                ('token_count', models.TextField(verbose_name='Количество токенов')),
                ('usd_count', models.TextField(verbose_name='Стоймость в долларах')),
                ('usd_in', models.TextField(verbose_name='Вложения в долларах')),
            ],
        ),
        migrations.DeleteModel(
            name='UserBill',
        ),
    ]
