# Generated by Django 3.2.13 on 2022-06-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0004_userusdacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavatars',
            name='imgur_link_small',
            field=models.TextField(default=123, verbose_name='Ссылка на миниатюру'),
            preserve_default=False,
        ),
    ]
