# Generated by Django 3.2.13 on 2022-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='Тикет')),
                ('current_buy_price', models.TextField(verbose_name='Цена покупки')),
                ('current_sell_price', models.TextField(verbose_name='Цена продажи')),
                ('avg_price', models.TextField(verbose_name='Средняя цена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='ETH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='Тикет')),
                ('current_buy_price', models.TextField(verbose_name='Цена покупки')),
                ('current_sell_price', models.TextField(verbose_name='Цена продажи')),
                ('avg_price', models.TextField(verbose_name='Средняя цена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='LTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='Тикет')),
                ('current_buy_price', models.TextField(verbose_name='Цена покупки')),
                ('current_sell_price', models.TextField(verbose_name='Цена продажи')),
                ('avg_price', models.TextField(verbose_name='Средняя цена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='XRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='Тикет')),
                ('current_buy_price', models.TextField(verbose_name='Цена покупки')),
                ('current_sell_price', models.TextField(verbose_name='Цена продажи')),
                ('avg_price', models.TextField(verbose_name='Средняя цена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='ZEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='Тикет')),
                ('current_buy_price', models.TextField(verbose_name='Цена покупки')),
                ('current_sell_price', models.TextField(verbose_name='Цена продажи')),
                ('avg_price', models.TextField(verbose_name='Средняя цена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.RenameModel(
            old_name='Quotes',
            new_name='BTC',
        ),
    ]
