# Generated by Django 3.2.13 on 2022-05-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20220531_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BTC',
        ),
    ]
