# Generated by Django 3.2.13 on 2022-05-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('is_moderator', models.BooleanField(default=False)),
            ],
        ),
    ]
