# Generated by Django 3.2.13 on 2022-05-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_singup_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='adress',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
