# Generated by Django 3.2.13 on 2022-05-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_singup_page', '0003_auto_20220526_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='adress',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(default='Uganda', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=10),
        ),
    ]
