# Generated by Django 3.2.13 on 2022-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_singup_page', '0006_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='username')),
                ('is_verificate', models.BooleanField(verbose_name='is_verificate')),
            ],
        ),
    ]
